# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mips.xdc

# IP: ip/InstrROM/InstrROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==InstrROM || ORIG_REF_NAME==InstrROM} -quiet] -quiet

# IP: ip/DataRAM/DataRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DataRAM || ORIG_REF_NAME==DataRAM} -quiet] -quiet

# XDC: d:/Users/hehey/Documents/MIPSproject_nexys/MIPSproject.gen/sources_1/ip/InstrROM/InstrROM_ooc.xdc

# XDC: d:/Users/hehey/Documents/MIPSproject_nexys/MIPSproject.gen/sources_1/ip/DataRAM/DataRAM_ooc.xdc
