#clk
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
#reset
set_property PACKAGE_PIN V10 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
#--------------------------------LED
set_property PACKAGE_PIN U13 [get_ports LED[7]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[7]]
set_property PACKAGE_PIN K2 [get_ports LED[6]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[6]]
set_property PACKAGE_PIN T14 [get_ports LED[5]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[5]]
set_property PACKAGE_PIN P14 [get_ports LED[4]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[4]]
set_property PACKAGE_PIN J14 [get_ports LED[3]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[3]]

set_property PACKAGE_PIN T9 [get_ports LED[2]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[2]]
set_property PACKAGE_PIN J18 [get_ports LED[1]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[1]]
set_property PACKAGE_PIN J17 [get_ports LED[0]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[0]]
#--------------------HEX
set_property PACKAGE_PIN T10 [get_ports HEX[0]]
set_property IOSTANDARD LVCMOS33 [get_ports HEX[0]]
set_property PACKAGE_PIN R10 [get_ports HEX[1]]
set_property IOSTANDARD LVCMOS33 [get_ports HEX[1]]
set_property PACKAGE_PIN K16 [get_ports HEX[2]]
set_property IOSTANDARD LVCMOS33 [get_ports HEX[2]]
set_property PACKAGE_PIN K13 [get_ports HEX[3]]
set_property IOSTANDARD LVCMOS33 [get_ports HEX[3]]

set_property PACKAGE_PIN P15 [get_ports HEX[4]]
set_property IOSTANDARD LVCMOS33 [get_ports HEX[4]]
set_property PACKAGE_PIN T11 [get_ports HEX[5]]
set_property IOSTANDARD LVCMOS33 [get_ports HEX[5]]
set_property PACKAGE_PIN L18 [get_ports HEX[6]]
set_property IOSTANDARD LVCMOS33 [get_ports HEX[6]]
set_property PACKAGE_PIN H15 [get_ports HEX[7]]
set_property IOSTANDARD LVCMOS33 [get_ports HEX[7]]
#---------------------Select
set_property PACKAGE_PIN U11 [get_ports select]
set_property IOSTANDARD LVCMOS33 [get_ports select]